### ISSUE TITLE
submission.getCommentCount() returns a positive integer, but submission.getComments() returns null

### ISSUE THREAD

**Issue by zjs** [thatJavaNerd/JRAW#73] opened 2015-05-24 02:16 UTC
Sample code (excluding the construction of the `RedditClient`):
```
SubredditPaginator subredditPaginator = new SubredditPaginator(redditClient, "science");

Listing<Submission> listing = subredditPaginator.next();

Submission submission = listing.get(0);
System.out.println(submission.getCommentCount()); // outputs 306

CommentNode comments = submission.getComments();
System.out.println(comments); // outputs null
```

Using 0.7.1 from jCenter.

**Comment by thatJavaNerd** [comment] 2015-05-26 13:37
Duplicate of #29, #44, and #66.

Please read the documentation for the [`SubredditPaginator`](http://thatjavanerd.github.io/JRAW/docs/0.7.1/net/dean/jraw/paginators/SubredditPaginator.html) class:

>Please note that the Submissions that are returned by this Paginator will *always* have null comments. The reason for this is that reddit does not include them in general pagination (which is what this Paginator does). Only when that Submission is queried directly does reddit give you that post's comments.
To query a Submission directly, use [`RedditClient.getSubmission(String)`](http://thatjavanerd.github.io/JRAW/docs/0.7.1/net/dean/jraw/paginators/SubredditPaginator.html).

**Closed by thatJavaNerd** 2015-05-26 13:37 UTC
Labels: duplicate
